version: 2.1

orbs:
  maven: circleci/maven@0.0.12

jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0.1-jdk

workflows:
  maven_test:
      - maven/test # checkout, build, test, and upload test results
